package version

const CURRENT_BACKEND_VERSION = "0.26.3"
const CURRENT_FRONTEND_VERSION = "0.26.3"

const RELEASED_APP_VERSION = "2026.3.5"
const RELEASED_BACKEND_VERSION = "0.26.3"
const RELEASED_FRONTEND_VERSION = "0.26.3"
