package version

const CURRENT_BACKEND_VERSION = "0.29.0"
const CURRENT_FRONTEND_VERSION = "0.29.1"

const RELEASED_APP_VERSION = "2026.4.2"
const RELEASED_BACKEND_VERSION = "0.29.0"
const RELEASED_FRONTEND_VERSION = "0.29.1"
